# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: Vantagens: 1. Uma vez definida uma função, é possível utilizá-la novamente ao longo do código, sem precisar reescrever todo o código da função. 2. Facilita a organização 3. Facilita a correção de erros 
Características: Funções devem ter entrada e saída (exceto procedimentos, que não retornam nada). Funções devem conter apenas uma tarefa e retornar apenas um valor. 

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

## 02 – Descreva o racional da sua resposta:

R.: O racional é basicamente o mesmo da atividade anterior. Contudo, a seleção dos valores acontece dentro da função (que pode ser chamada diversas vezes dentro de um mesmo código). Nesse caso ela retorna três valores diferentes que correspondem ao array de valores aleatórios, a quantidade de valores maiores que 10 e os valores em si.  

## 03 – Desenhe o fluxograma da resposta:

<img src="./img/fluxograma1atv12.png" width = "400"  /> 

## 04 – Escreva o programa em Python:

In [50]:
import numpy as np

def maiores_que_10():

    arr = np.random.normal(loc=10, scale=3, size=5)
    
    
    valores_maiores = arr[arr > 10]
    
    
    quantidade = np.sum(arr > 10)
    
   
    return arr, quantidade, valores_maiores


array, qtd, maiores = maiores_que_10()

print(array)
print("Quantidade > 10:", qtd)
print( maiores)

[11.31178809 11.53425298 12.15490249 10.81345985 10.69257958]
Quantidade > 10: 5
[11.31178809 11.53425298 12.15490249 10.81345985 10.69257958]


## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

Sim, bastaria mudar os parâmetros:

In [66]:
import numpy as np

def maiores_que_20():

    arr = np.random.normal(loc=10, scale=3, size=5)
    
    
    valores_maiores = arr[arr > 20]
    quantidade = np.sum(arr > 20)
    
   
    return arr, quantidade, valores_maiores



array1, qtd1, maiores1 = maiores_que_20()

print(array1)
print("Quantidade > 20:", qtd1)
print( maiores1)

[11.10275565  9.18851943  9.3629207   8.67756341 11.86084986]
Quantidade > 20: 0
[]


## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

## 06 – Descreva o racional da sua resposta:

R.: Criei uma função em que a variável soma recebe a soma de um conjunto de valores (input). Em seguida é calculada a quantidade de valores e calculada a média dividindo a soma pela quantidade de valores. Fora da função, defini a variável "valores", que recebe o input. Esse input é convertido em uma lista de floats na linha 10. Por fim, o código chama a função e printa o valor retornado por ela.

## 07 – Desenhe o fluxograma da resposta:

<img src="./img/fluxograma2atv12.png" width = "400"  /> 

## 08 – Escreva o programa em Python:

In [78]:

def calcular_media(valores):
    soma = sum(valores)
    quantidade = len(valores)
    media = soma / quantidade
    return media

valores = input("digite os valores separados por espaço")

valores = [float(x) for x in valores.split()]

print (calcular_media(valores))

25.0


## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [100]:
def dividir_objetos(obj1, obj2):
    print("Objeto 1:")
    print("Classe:", type(obj1))
    print("Valor:", obj1)
    
    print("Objeto 2:")
    print("Classe:", type(obj2))
    print("Valor:", obj2)

    if type(obj1) == str:
        return "Impossível dividir um objeto str."   #Tinha feito essa parte pensando em instanciar uma variável direto no código. Mas no input mesmo coloquei a conversão para float.
    
    if type(obj2) == str:
        return "Impossível dividir um objeto str."
    
    if type(obj1) == bool:
        return "Impossível dividir um objeto bool."
    
    if type(obj2) == bool:
        return "Impossível dividir um objeto bool."
    
    if obj2 == 0:
        return "Erro: divisão por zero não é permitida."
    
    resultado = obj1 / obj2
    return resultado

#a = 2
#b = 4

#a = True
#b = "string"

a = float(input("Digite o primeiro valor"))
b = float(input("Digite o segundo valor")) 

print("Resultado da divisão:", dividir_objetos(a, b))

Objeto 1:
Classe: <class 'float'>
Valor: 4.0
Objeto 2:
Classe: <class 'float'>
Valor: 6.0
Resultado da divisão: 0.6666666666666666


## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [99]:
def dividir_compostos(obj1, obj2):
    print("Objeto 1:")
    print("Classe:", type(obj1))
    print("Valor:", obj1)
    
    print("Objeto 2:")
    print("Classe:", type(obj2))
    print("Valor:", obj2)
    

    if not isinstance(obj1, list) or not isinstance(obj2, list):   #verificando tipo
        return "Erro: os objetos devem ser listas."
    

    if len(obj1) != len(obj2):
        return "Erro: listas devem ter o mesmo tamanho."  #verificando tamanho
    
    resultado = []
    
    for a, b in zip(obj1, obj2):
        if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
            return "Erro: todos os elementos devem ser numéricos."
        
        if b == 0:
            return "Erro: divisão por zero em um dos elementos."
        
        resultado.append(a / b)
    
    return resultado


lista1 = [10, 20, 30]
lista2 = [2, 4, 5]

print("Resultado:", dividir_compostos(lista1, lista2))

Objeto 1:
Classe: <class 'list'>
Valor: [10, 20, 30]
Objeto 2:
Classe: <class 'list'>
Valor: [2, 4, 5]
Resultado: [5.0, 5.0, 6.0]
